version: 0.1

phases:
  install:
    commands:
      - npm install
  # build:
  #   commands:
  #     - npm run dev
  # post_build:
  #   commands:
  #     - mkdir -p build
  #     - npm install -g serverless